#!/bin/bash
COUNT=0
REFRESH=60
until [ $(curl -o /dev/null --silent --head --write-out '%{http_code}\n' $1) -eq 404 ]; do
	echo "Thread ${1} [still] alive"
	while read -r image; do
		if [ $(echo ${image} | sed 's/.*\///;s/\..*//') -gt ${COUNT} ]; then
			echo "Downloading ${image}"
			wget -q ${image}
			COUNT=$(echo ${image} | sed 's/.*\///;s/\..*//')
		fi
	done < <(wget -q -O - ${1} | grep -Eo 'i.4cdn.org/[^"]+' | uniq)
	echo "End of page, refreshing in ${REFRESH} second(s)"
	sleep ${REFRESH}
done
echo "Thread 404'd"
